apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: app-container
    image: 022569946651.dkr.ecr.us-east-1.amazonaws.com/project:latest
    ports:
      - containerPort: 5000
        name: http-web-svc
