apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: http-web-svc
